src/Entity/Actor.php
<?php

namespace App\Entity;

use App\Repository\ActorRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActorRepository::class)]
class Actor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $token_api = null;

    #[ORM\Column(nullable: true)]
    private ?int $annuaire_user_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $annuaire_fullname = null;

    #[ORM\Column(nullable: true)]
    private ?int $annuaire_fonction_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $annuaire_fonction_libelle = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $annuaire_lieux_exercices_user = null;

    #[ORM\Column(nullable: true)]
    private ?int $profession_dmi_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $matricule = null;

    #[ORM\Column(nullable: true)]
    private ?int $annuaire_etablissement_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $annuaire_etablissement_libelle = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_etablissement_selectionne = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $annuaire_service_id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $annuaire_service_designation = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mobile = null;

    #[ORM\Column(nullable: true)]
    private ?bool $admin_dmi = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getTokenApi(): ?string
    {
        return $this->token_api;
    }

    public function setTokenApi(?string $token_api): static
    {
        $this->token_api = $token_api;

        return $this;
    }

    public function getAnnuaireUserId(): ?int
    {
        return $this->annuaire_user_id;
    }

    public function setAnnuaireUserId(?int $annuaire_user_id): static
    {
        $this->annuaire_user_id = $annuaire_user_id;

        return $this;
    }

    public function getAnnuaireFullname(): ?string
    {
        return $this->annuaire_fullname;
    }

    public function setAnnuaireFullname(?string $annuaire_fullname): static
    {
        $this->annuaire_fullname = $annuaire_fullname;

        return $this;
    }

    public function getAnnuaireFonctionId(): ?int
    {
        return $this->annuaire_fonction_id;
    }

    public function setAnnuaireFonctionId(?int $annuaire_fonction_id): static
    {
        $this->annuaire_fonction_id = $annuaire_fonction_id;

        return $this;
    }

    public function getAnnuaireFonctionLibelle(): ?string
    {
        return $this->annuaire_fonction_libelle;
    }

    public function setAnnuaireFonctionLibelle(?string $annuaire_fonction_libelle): static
    {
        $this->annuaire_fonction_libelle = $annuaire_fonction_libelle;

        return $this;
    }

    public function getAnnuaireLieuxExercicesUser(): ?string
    {
        return $this->annuaire_lieux_exercices_user;
    }

    public function setAnnuaireLieuxExercicesUser(?string $annuaire_lieux_exercices_user): static
    {
        $this->annuaire_lieux_exercices_user = $annuaire_lieux_exercices_user;

        return $this;
    }

    public function getProfessionDmiId(): ?int
    {
        return $this->profession_dmi_id;
    }

    public function setProfessionDmiId(?int $profession_dmi_id): static
    {
        $this->profession_dmi_id = $profession_dmi_id;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(?string $matricule): static
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getAnnuaireEtablissementId(): ?int
    {
        return $this->annuaire_etablissement_id;
    }

    public function setAnnuaireEtablissementId(?int $annuaire_etablissement_id): static
    {
        $this->annuaire_etablissement_id = $annuaire_etablissement_id;

        return $this;
    }

    public function getAnnuaireEtablissementLibelle(): ?string
    {
        return $this->annuaire_etablissement_libelle;
    }

    public function setAnnuaireEtablissementLibelle(?string $annuaire_etablissement_libelle): static
    {
        $this->annuaire_etablissement_libelle = $annuaire_etablissement_libelle;

        return $this;
    }

    public function isEtablissementSelectionne(): ?bool
    {
        return $this->is_etablissement_selectionne;
    }

    public function setEtablissementSelectionne(?bool $is_etablissement_selectionne): static
    {
        $this->is_etablissement_selectionne = $is_etablissement_selectionne;

        return $this;
    }

    public function getAnnuaireServiceId(): ?string
    {
        return $this->annuaire_service_id;
    }

    public function setAnnuaireServiceId(?string $annuaire_service_id): static
    {
        $this->annuaire_service_id = $annuaire_service_id;

        return $this;
    }

    public function getAnnuaireServiceDesignation(): ?string
    {
        return $this->annuaire_service_designation;
    }

    public function setAnnuaireServiceDesignation(?string $annuaire_service_designation): static
    {
        $this->annuaire_service_designation = $annuaire_service_designation;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): static
    {
        $this->mobile = $mobile;

        return $this;
    }

    public function isAdminDmi(): ?bool
    {
        return $this->admin_dmi;
    }

    public function setAdminDmi(?bool $admin_dmi): static
    {
        $this->admin_dmi = $admin_dmi;

        return $this;
    }
}

templates/includes/header.html.twig
<!--begin::Header-->
<div id="kt_header" style="" class="header align-items-stretch">
    <!--begin::Brand-->
    <div class="header-brand">
        <!--begin::Logo-->
        <a href="/">
            <h1 class="mb-0" style="color: #ffffff">Project Stage<span style="font-size: 12px;"> 0.0.0.0</span></h1>
            <h6 class="mb-0 sspl-etablissement-courant" style="color: #ffffff">2024</h6>
        </a>
        {#                                <a href="/">#}
        {#                                    <img alt="Logo" src="assets/media/logos/sisspl.png" class="h-50px h-50px bg-white">#}
        {#                                    <h6 class="mb-0 sspl-etablissement-courant" style="color: #ffffff">{{ app.user.annuaireEtablissementLibelle }}</h6>#}
        {#                                </a>#}
        <!--end::Logo-->
        <!--begin::Aside minimize-->
        <div id="kt_aside_toggle" class="btn btn-icon w-auto px-0 btn-active-color-primary aside-minimize" data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body" data-kt-toggle-name="aside-minimize">
            <!--begin::Svg Icon | path: icons/duotune/arrows/arr092.svg-->
            <span class="svg-icon svg-icon-1 me-n1 minimize-default">
									<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<rect opacity="0.3" x="8.5" y="11" width="12" height="2" rx="1" fill="currentColor" />
										<path d="M10.3687 11.6927L12.1244 10.2297C12.5946 9.83785 12.6268 9.12683 12.194 8.69401C11.8043 8.3043 11.1784 8.28591 10.7664 8.65206L7.84084 11.2526C7.39332 11.6504 7.39332 12.3496 7.84084 12.7474L10.7664 15.3479C11.1784 15.7141 11.8043 15.6957 12.194 15.306C12.6268 14.8732 12.5946 14.1621 12.1244 13.7703L10.3687 12.3073C10.1768 12.1474 10.1768 11.8526 10.3687 11.6927Z" fill="currentColor" />
										<path opacity="0.5" d="M16 5V6C16 6.55228 15.5523 7 15 7C14.4477 7 14 6.55228 14 6C14 5.44772 13.5523 5 13 5H6C5.44771 5 5 5.44772 5 6V18C5 18.5523 5.44771 19 6 19H13C13.5523 19 14 18.5523 14 18C14 17.4477 14.4477 17 15 17C15.5523 17 16 17.4477 16 18V19C16 20.1046 15.1046 21 14 21H5C3.89543 21 3 20.1046 3 19V5C3 3.89543 3.89543 3 5 3H14C15.1046 3 16 3.89543 16 5Z" fill="currentColor" />
									</svg>
								</span>
            <!--end::Svg Icon-->
            <!--begin::Svg Icon | path: icons/duotune/arrows/arr076.svg-->
            <span class="svg-icon svg-icon-1 minimize-active">
									<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<rect opacity="0.3" width="12" height="2" rx="1" transform="matrix(-1 0 0 1 15.5 11)" fill="currentColor" />
										<path d="M13.6313 11.6927L11.8756 10.2297C11.4054 9.83785 11.3732 9.12683 11.806 8.69401C12.1957 8.3043 12.8216 8.28591 13.2336 8.65206L16.1592 11.2526C16.6067 11.6504 16.6067 12.3496 16.1592 12.7474L13.2336 15.3479C12.8216 15.7141 12.1957 15.6957 11.806 15.306C11.3732 14.8732 11.4054 14.1621 11.8756 13.7703L13.6313 12.3073C13.8232 12.1474 13.8232 11.8526 13.6313 11.6927Z" fill="currentColor" />
										<path d="M8 5V6C8 6.55228 8.44772 7 9 7C9.55228 7 10 6.55228 10 6C10 5.44772 10.4477 5 11 5H18C18.5523 5 19 5.44772 19 6V18C19 18.5523 18.5523 19 18 19H11C10.4477 19 10 18.5523 10 18C10 17.4477 9.55228 17 9 17C8.44772 17 8 17.4477 8 18V19C8 20.1046 8.89543 21 10 21H19C20.1046 21 21 20.1046 21 19V5C21 3.89543 20.1046 3 19 3H10C8.89543 3 8 3.89543 8 5Z" fill="currentColor" />
									</svg>
								</span>
            <!--end::Svg Icon-->
        </div>
        <!--end::Aside minimize-->
        <!--begin::Aside toggle-->
        <div class="d-flex align-items-center d-lg-none ms-n3 me-1" title="Show aside menu">
            <div class="btn btn-icon btn-active-color-primary w-30px h-30px" id="kt_aside_mobile_toggle">
                <!--begin::Svg Icon | path: icons/duotune/abstract/abs015.svg-->
                <span class="svg-icon svg-icon-1">
										<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path d="M21 7H3C2.4 7 2 6.6 2 6V4C2 3.4 2.4 3 3 3H21C21.6 3 22 3.4 22 4V6C22 6.6 21.6 7 21 7Z" fill="currentColor" />
											<path opacity="0.3" d="M21 14H3C2.4 14 2 13.6 2 13V11C2 10.4 2.4 10 3 10H21C21.6 10 22 10.4 22 11V13C22 13.6 21.6 14 21 14ZM22 20V18C22 17.4 21.6 17 21 17H3C2.4 17 2 17.4 2 18V20C2 20.6 2.4 21 3 21H21C21.6 21 22 20.6 22 20Z" fill="currentColor" />
										</svg>
									</span>
                <!--end::Svg Icon-->
            </div>
        </div>
        <!--end::Aside toggle-->
    </div>
    <!--end::Brand-->
    <!--begin::Toolbar-->
    <div class="toolbar d-flex align-items-stretch">
        <!--begin::Toolbar container-->
        <div class="container-fluid py-6 py-lg-0 d-flex flex-column flex-lg-row align-items-lg-stretch justify-content-lg-between">

            {% block breadcrumb %}{% endblock %}


        </div>
        <!--end::Toolbar container-->
    </div>
    <!--end::Toolbar-->
</div>
<!--end::Header-->

templates/includes/side.html.twig
<!--begin::Aside-->
<div id="kt_aside" class="aside" data-kt-drawer="true" data-kt-drawer-name="aside"
     data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true"
     data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start"
     data-kt-drawer-toggle="#kt_aside_mobile_toggle">
    <div class="aside-toolbar flex-column-auto" id="kt_aside_toolbar">
        <div class="aside-user d-flex align-items-sm-center justify-content-center py-5">
            <div class="symbol symbol-50px">
                <img src="{{ asset('assets/media/avatars/blank.png') }}" alt=""/>
            </div>
            <div class="aside-user-info flex-row-fluid flex-wrap ms-5">
                <div class="d-flex">
                    <div class="flex-grow-1 me-2">
                        <a href="#" class="text-white text-hover-primary fs-6 fw-bold">
                            test
                        </a>
                        <span class="text-gray-600 fw-semibold d-block fs-8 mb-1 sspl-fonction-courant">
                            user
                        </span>
                    </div>
                    <div class="me-n2">
                        <a href="#" class="btn btn-icon btn-sm btn-active-color-primary mt-n2"
                           data-kt-menu-trigger="click" data-kt-menu-placement="bottom-start"
                           data-kt-menu-overflow="true">
                            <span class="svg-icon svg-icon-muted svg-icon-1">
												<svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                                     xmlns="http://www.w3.org/2000/svg">
													<path opacity="0.3"
                                                          d="M22.1 11.5V12.6C22.1 13.2 21.7 13.6 21.2 13.7L19.9 13.9C19.7 14.7 19.4 15.5 18.9 16.2L19.7 17.2999C20 17.6999 20 18.3999 19.6 18.7999L18.8 19.6C18.4 20 17.8 20 17.3 19.7L16.2 18.9C15.5 19.3 14.7 19.7 13.9 19.9L13.7 21.2C13.6 21.7 13.1 22.1 12.6 22.1H11.5C10.9 22.1 10.5 21.7 10.4 21.2L10.2 19.9C9.4 19.7 8.6 19.4 7.9 18.9L6.8 19.7C6.4 20 5.7 20 5.3 19.6L4.5 18.7999C4.1 18.3999 4.1 17.7999 4.4 17.2999L5.2 16.2C4.8 15.5 4.4 14.7 4.2 13.9L2.9 13.7C2.4 13.6 2 13.1 2 12.6V11.5C2 10.9 2.4 10.5 2.9 10.4L4.2 10.2C4.4 9.39995 4.7 8.60002 5.2 7.90002L4.4 6.79993C4.1 6.39993 4.1 5.69993 4.5 5.29993L5.3 4.5C5.7 4.1 6.3 4.10002 6.8 4.40002L7.9 5.19995C8.6 4.79995 9.4 4.39995 10.2 4.19995L10.4 2.90002C10.5 2.40002 11 2 11.5 2H12.6C13.2 2 13.6 2.40002 13.7 2.90002L13.9 4.19995C14.7 4.39995 15.5 4.69995 16.2 5.19995L17.3 4.40002C17.7 4.10002 18.4 4.1 18.8 4.5L19.6 5.29993C20 5.69993 20 6.29993 19.7 6.79993L18.9 7.90002C19.3 8.60002 19.7 9.39995 19.9 10.2L21.2 10.4C21.7 10.5 22.1 11 22.1 11.5ZM12.1 8.59998C10.2 8.59998 8.6 10.2 8.6 12.1C8.6 14 10.2 15.6 12.1 15.6C14 15.6 15.6 14 15.6 12.1C15.6 10.2 14 8.59998 12.1 8.59998Z"
                                                          fill="currentColor"/>
													<path d="M17.1 12.1C17.1 14.9 14.9 17.1 12.1 17.1C9.30001 17.1 7.10001 14.9 7.10001 12.1C7.10001 9.29998 9.30001 7.09998 12.1 7.09998C14.9 7.09998 17.1 9.29998 17.1 12.1ZM12.1 10.1C11 10.1 10.1 11 10.1 12.1C10.1 13.2 11 14.1 12.1 14.1C13.2 14.1 14.1 13.2 14.1 12.1C14.1 11 13.2 10.1 12.1 10.1Z"
                                                          fill="currentColor"/>
												</svg>
											</span>
                        </a>
                        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px"
                             data-kt-menu="true">
                            <div class="menu-item px-5">
                                <a href="#" class="menu-link px-5">Déconnexion</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="aside-menu flex-column-fluid">
        <div class="hover-scroll-overlay-y px-2 my-5 my-lg-5" id="kt_aside_menu_wrapper" data-kt-scroll="true"
             data-kt-scroll-height="auto"
             data-kt-scroll-dependencies="{default: '#kt_aside_toolbar, #kt_aside_footer', lg: '#kt_header, #kt_aside_toolbar, #kt_aside_footer'}"
             data-kt-scroll-wrappers="#kt_aside_menu" data-kt-scroll-offset="5px">

            <div class="menu menu-column menu-title-gray-800 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-500"
                 id="#kt_aside_menu" data-kt-menu="true">

                <!--begin::Menu-->
                <div class="menu menu-rounded menu-column menu-active-bg menu-hover-bg menu-title-gray-700 fs-5 fw-semibold w-250px" id="#kt_aside_menu" data-kt-menu="true">
                    <div class="menu-item">
                        <div class="menu-content pb-2">
                            <span class="menu-section text-muted text-uppercase fs-7 fw-bold">Home</span>
                        </div>
                    </div>
                    <div class="menu-item">
                        <a href="{{ path('app_home') }}" class="menu-link  border-3 border-start border-transparent">
                            <span class="menu-icon">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <rect x="2" y="2" width="9" height="9" rx="2" fill="currentColor"/>
                                    <rect opacity="0.3" x="13" y="2" width="9" height="9" rx="2" fill="currentColor"/>
                                    <rect opacity="0.3" x="13" y="13" width="9" height="9" rx="2" fill="currentColor"/>
                                    <rect opacity="0.3" x="2" y="13" width="9" height="9" rx="2" fill="currentColor"/>
                                </svg>
                            </span>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </div>
                    <div class="menu-item pt-5">
                        <div class="menu-content pb-2">
                            <span class="menu-section text-muted text-uppercase fs-7 fw-bold">Autre</span>
                        </div>
                    </div>

                    <!--begin::Menu item Analyse hospitalière-->
                    <div class="menu-item">
                        <a href="{{ path('app_hospital') }}" class="menu-link  border-3 border-start border-transparent">
                            <span class="menu-icon">
                                <i class="bi bi-hospital fs-3"></i>
                            </span>
                            <span class="menu-title">Analyse hospitalière</span>
                        </a>
                    </div>
                    <!--end::menu hospitalière-->

                    <!--begin::Menu item Médecins-->
                    <div class="menu-item menu-sub-indention menu-accordion" data-kt-menu-trigger="click">
                        <!--begin::Menu link-->
                        <a href="#" class="menu-link py-3">
                            <span class="menu-icon">
                                <i class="fa-solid fa-user-doctor fs-3"></i>
                            </span>
                            <span class="menu-title">Médecins</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <!--end::Menu link-->

                        <!--begin::Menu sub-->
                        <div class="menu-sub menu-sub-accordion pt-3">
                            <!--begin::Menu item-->
                            <div class="menu-item">
                                <a href="#" class="menu-link py-3">
                    <span class="menu-bullet">
                        <span class="bullet bullet-dot"></span>
                    </span>
                                    <span class="menu-title">Découvrir</span>
                                </a>
                            </div>
                            <!--end::Menu item-->

                            <!--begin::Menu item-->
                            <div class="menu-item">
                                <a href="#" class="menu-link py-3">
                    <span class="menu-bullet">
                        <span class="bullet bullet-dot"></span>
                    </span>
                                    <span class="menu-title">Ajout / Modification</span>
                                </a>
                            </div>
                            <!--end::Menu item-->


                        </div>
                        <!--end::Menu-->


                    </div>
                    <!--end::menu Médecins-->

                    <!--begin::Menu item Patients-->
                    <div class="menu-item menu-sub-indention menu-accordion " data-kt-menu-trigger="click" >
                        <!--begin::Menu link-->
                        <a href="#" class="menu-link py-3 ">
                            <span class="menu-icon">
                                <i class="fa-duotone fa-solid fa-hospital-user fs-3"></i>
                            </span>
                            <span class="menu-title ">Patients</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <!--end::Menu link-->

                        <!--begin::Menu sub-->
                        <div class="menu-sub menu-sub-accordion pt-3">
                            <!--begin::Menu item-->
                            <div class="menu-item">
                                <a href="#" class="menu-link py-3">
                                    <span class="menu-bullet">
                                        <span class="bullet bullet-dot"></span>
                                    </span>
                                    <span class="menu-title">Découvrir</span>
                                </a>
                            </div>
                            <!--end::Menu item-->

                            <!--begin::Menu item-->
                            <div class="menu-item">
                                <a href="#" class="menu-link py-3">
                                    <span class="menu-bullet">
                                        <span class="bullet bullet-dot"></span>
                                    </span>
                                    <span class="menu-title">Ajout / Modification</span>
                                </a>
                            </div>
                            <!--end::Menu item-->


                        </div>
                        <!--end::Menu-->

                    </div>
                    <!--end::menu Patients-->

                </div>
                <!--end::menu-->
            </div>
            {#<!--begin::Footer-->#}
            {#<div class="aside-footer flex-column-auto py-5" id="kt_aside_footer">#}
                {#<a href="https://preview.keenthemes.com/html/metronic/docs" class="btn btn-flex btn-custom btn-primary w-100" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss-="click" title="200+ in-house components and 3rd-party plugins">#}
                    {#<span class="btn-label">#}
                        {#Docs & Components#}
                    {#</span>#}
                    {#<i class="ki-duotone ki-document ms-2 fs-2"><span class="path1"></span><span class="path2"></span></i>        </a>#}
            {#</div>#}
            {#<!--end::Footer-->#}
        </div>
    </div>

</div>
<!--end::Aside-->